# Gradle Properties
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Project Details
jvm_version=17

project_group=com.viaversion
project_name=ViaRewind-Legacy-Support
project_version=1.5.5-SNAPSHOT
project_description=Provides additional features for ViaRewind for Paper servers.

publish_owner_id=florianreuth
publish_owner_name=Florian Reuth
publish_owner_mail=git@florianreuth.de

# Hangar Publishing
minecraft_version_range=1.8-26.2
